//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.wsMontoReserva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="wsMontoReserva.ZWS_ZINT_CONF_MONTO_RESERVA")]
    public interface ZWS_ZINT_CONF_MONTO_RESERVA {
        
        // CODEGEN: Generating message contract since the operation ZintConfMontoReserva is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_CONF_MONTO_RESERVA:Zint" +
            "ConfMontoReservaRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Presentacion.wsMontoReserva.ZintConfMontoReservaResponse1 ZintConfMontoReserva(Presentacion.wsMontoReserva.ZintConfMontoReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZWS_ZINT_CONF_MONTO_RESERVA:Zint" +
            "ConfMontoReservaRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentacion.wsMontoReserva.ZintConfMontoReservaResponse1> ZintConfMontoReservaAsync(Presentacion.wsMontoReserva.ZintConfMontoReservaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintConfMontoReserva : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iPosicionField;
        
        private string iReservaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IPosicion {
            get {
                return this.iPosicionField;
            }
            set {
                this.iPosicionField = value;
                this.RaisePropertyChanged("IPosicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IReserva {
            get {
                return this.iReservaField;
            }
            set {
                this.iReservaField = value;
                this.RaisePropertyChanged("IReserva");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZintConfMontoReservaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eSaldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ESaldo {
            get {
                return this.eSaldoField;
            }
            set {
                this.eSaldoField = value;
                this.RaisePropertyChanged("ESaldo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintConfMontoReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public Presentacion.wsMontoReserva.ZintConfMontoReserva ZintConfMontoReserva;
        
        public ZintConfMontoReservaRequest() {
        }
        
        public ZintConfMontoReservaRequest(Presentacion.wsMontoReserva.ZintConfMontoReserva ZintConfMontoReserva) {
            this.ZintConfMontoReserva = ZintConfMontoReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZintConfMontoReservaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public Presentacion.wsMontoReserva.ZintConfMontoReservaResponse ZintConfMontoReservaResponse;
        
        public ZintConfMontoReservaResponse1() {
        }
        
        public ZintConfMontoReservaResponse1(Presentacion.wsMontoReserva.ZintConfMontoReservaResponse ZintConfMontoReservaResponse) {
            this.ZintConfMontoReservaResponse = ZintConfMontoReservaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_ZINT_CONF_MONTO_RESERVAChannel : Presentacion.wsMontoReserva.ZWS_ZINT_CONF_MONTO_RESERVA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_ZINT_CONF_MONTO_RESERVAClient : System.ServiceModel.ClientBase<Presentacion.wsMontoReserva.ZWS_ZINT_CONF_MONTO_RESERVA>, Presentacion.wsMontoReserva.ZWS_ZINT_CONF_MONTO_RESERVA {
        
        public ZWS_ZINT_CONF_MONTO_RESERVAClient() {
        }
        
        public ZWS_ZINT_CONF_MONTO_RESERVAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_ZINT_CONF_MONTO_RESERVAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_CONF_MONTO_RESERVAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_ZINT_CONF_MONTO_RESERVAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.wsMontoReserva.ZintConfMontoReservaResponse1 Presentacion.wsMontoReserva.ZWS_ZINT_CONF_MONTO_RESERVA.ZintConfMontoReserva(Presentacion.wsMontoReserva.ZintConfMontoReservaRequest request) {
            return base.Channel.ZintConfMontoReserva(request);
        }
        
        public Presentacion.wsMontoReserva.ZintConfMontoReservaResponse ZintConfMontoReserva(Presentacion.wsMontoReserva.ZintConfMontoReserva ZintConfMontoReserva1) {
            Presentacion.wsMontoReserva.ZintConfMontoReservaRequest inValue = new Presentacion.wsMontoReserva.ZintConfMontoReservaRequest();
            inValue.ZintConfMontoReserva = ZintConfMontoReserva1;
            Presentacion.wsMontoReserva.ZintConfMontoReservaResponse1 retVal = ((Presentacion.wsMontoReserva.ZWS_ZINT_CONF_MONTO_RESERVA)(this)).ZintConfMontoReserva(inValue);
            return retVal.ZintConfMontoReservaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.wsMontoReserva.ZintConfMontoReservaResponse1> Presentacion.wsMontoReserva.ZWS_ZINT_CONF_MONTO_RESERVA.ZintConfMontoReservaAsync(Presentacion.wsMontoReserva.ZintConfMontoReservaRequest request) {
            return base.Channel.ZintConfMontoReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.wsMontoReserva.ZintConfMontoReservaResponse1> ZintConfMontoReservaAsync(Presentacion.wsMontoReserva.ZintConfMontoReserva ZintConfMontoReserva) {
            Presentacion.wsMontoReserva.ZintConfMontoReservaRequest inValue = new Presentacion.wsMontoReserva.ZintConfMontoReservaRequest();
            inValue.ZintConfMontoReserva = ZintConfMontoReserva;
            return ((Presentacion.wsMontoReserva.ZWS_ZINT_CONF_MONTO_RESERVA)(this)).ZintConfMontoReservaAsync(inValue);
        }
    }
}
