//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LogicaNegocio.wsBccrRds1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExtractosSoap", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContratoDatos))]
    public partial class Extractos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarCuponesPorFechaCancelacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCuponesPorFechaConstitucionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCuponesPorFechaValorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarValoresPorFechaCancelacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarValoresPorFechaConstitucionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarValoresPorFechaValorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResumenSaldosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Extractos() {
            this.Url = "http://172.19.20.99:94/extractos.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarCuponesPorFechaCancelacionCompletedEventHandler ListarCuponesPorFechaCancelacionCompleted;
        
        /// <remarks/>
        public event ListarCuponesPorFechaConstitucionCompletedEventHandler ListarCuponesPorFechaConstitucionCompleted;
        
        /// <remarks/>
        public event ListarCuponesPorFechaValorCompletedEventHandler ListarCuponesPorFechaValorCompleted;
        
        /// <remarks/>
        public event ListarValoresPorFechaCancelacionCompletedEventHandler ListarValoresPorFechaCancelacionCompleted;
        
        /// <remarks/>
        public event ListarValoresPorFechaConstitucionCompletedEventHandler ListarValoresPorFechaConstitucionCompleted;
        
        /// <remarks/>
        public event ListarValoresPorFechaValorCompletedEventHandler ListarValoresPorFechaValorCompleted;
        
        /// <remarks/>
        public event ResumenSaldosCompletedEventHandler ResumenSaldosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.18.4.96/Servicios/Extractos.asmx/ListarCuponesPorFechaCancelacion", RequestNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", ResponseNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cupon[] ListarCuponesPorFechaCancelacion(System.DateTime fechaCancelacion, string tipo_deuda) {
            object[] results = this.Invoke("ListarCuponesPorFechaCancelacion", new object[] {
                        fechaCancelacion,
                        tipo_deuda});
            return ((Cupon[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCuponesPorFechaCancelacionAsync(System.DateTime fechaCancelacion, string tipo_deuda) {
            this.ListarCuponesPorFechaCancelacionAsync(fechaCancelacion, tipo_deuda, null);
        }
        
        /// <remarks/>
        public void ListarCuponesPorFechaCancelacionAsync(System.DateTime fechaCancelacion, string tipo_deuda, object userState) {
            if ((this.ListarCuponesPorFechaCancelacionOperationCompleted == null)) {
                this.ListarCuponesPorFechaCancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCuponesPorFechaCancelacionOperationCompleted);
            }
            this.InvokeAsync("ListarCuponesPorFechaCancelacion", new object[] {
                        fechaCancelacion,
                        tipo_deuda}, this.ListarCuponesPorFechaCancelacionOperationCompleted, userState);
        }
        
        private void OnListarCuponesPorFechaCancelacionOperationCompleted(object arg) {
            if ((this.ListarCuponesPorFechaCancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCuponesPorFechaCancelacionCompleted(this, new ListarCuponesPorFechaCancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.18.4.96/Servicios/Extractos.asmx/ListarCuponesPorFechaConstitucion", RequestNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", ResponseNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cupon[] ListarCuponesPorFechaConstitucion(System.DateTime fecConstitucion, string tipo_deuda) {
            object[] results = this.Invoke("ListarCuponesPorFechaConstitucion", new object[] {
                        fecConstitucion,
                        tipo_deuda});
            return ((Cupon[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCuponesPorFechaConstitucionAsync(System.DateTime fecConstitucion, string tipo_deuda) {
            this.ListarCuponesPorFechaConstitucionAsync(fecConstitucion, tipo_deuda, null);
        }
        
        /// <remarks/>
        public void ListarCuponesPorFechaConstitucionAsync(System.DateTime fecConstitucion, string tipo_deuda, object userState) {
            if ((this.ListarCuponesPorFechaConstitucionOperationCompleted == null)) {
                this.ListarCuponesPorFechaConstitucionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCuponesPorFechaConstitucionOperationCompleted);
            }
            this.InvokeAsync("ListarCuponesPorFechaConstitucion", new object[] {
                        fecConstitucion,
                        tipo_deuda}, this.ListarCuponesPorFechaConstitucionOperationCompleted, userState);
        }
        
        private void OnListarCuponesPorFechaConstitucionOperationCompleted(object arg) {
            if ((this.ListarCuponesPorFechaConstitucionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCuponesPorFechaConstitucionCompleted(this, new ListarCuponesPorFechaConstitucionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.18.4.96/Servicios/Extractos.asmx/ListarCuponesPorFechaValor", RequestNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", ResponseNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cupon[] ListarCuponesPorFechaValor(System.DateTime fechaValor, string tipo_deuda) {
            object[] results = this.Invoke("ListarCuponesPorFechaValor", new object[] {
                        fechaValor,
                        tipo_deuda});
            return ((Cupon[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCuponesPorFechaValorAsync(System.DateTime fechaValor, string tipo_deuda) {
            this.ListarCuponesPorFechaValorAsync(fechaValor, tipo_deuda, null);
        }
        
        /// <remarks/>
        public void ListarCuponesPorFechaValorAsync(System.DateTime fechaValor, string tipo_deuda, object userState) {
            if ((this.ListarCuponesPorFechaValorOperationCompleted == null)) {
                this.ListarCuponesPorFechaValorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCuponesPorFechaValorOperationCompleted);
            }
            this.InvokeAsync("ListarCuponesPorFechaValor", new object[] {
                        fechaValor,
                        tipo_deuda}, this.ListarCuponesPorFechaValorOperationCompleted, userState);
        }
        
        private void OnListarCuponesPorFechaValorOperationCompleted(object arg) {
            if ((this.ListarCuponesPorFechaValorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCuponesPorFechaValorCompleted(this, new ListarCuponesPorFechaValorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.18.4.96/Servicios/Extractos.asmx/ListarValoresPorFechaCancelacion", RequestNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", ResponseNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Valor[] ListarValoresPorFechaCancelacion(System.DateTime fechaCancelacion, string tipo_deuda) {
            object[] results = this.Invoke("ListarValoresPorFechaCancelacion", new object[] {
                        fechaCancelacion,
                        tipo_deuda});
            return ((Valor[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarValoresPorFechaCancelacionAsync(System.DateTime fechaCancelacion, string tipo_deuda) {
            this.ListarValoresPorFechaCancelacionAsync(fechaCancelacion, tipo_deuda, null);
        }
        
        /// <remarks/>
        public void ListarValoresPorFechaCancelacionAsync(System.DateTime fechaCancelacion, string tipo_deuda, object userState) {
            if ((this.ListarValoresPorFechaCancelacionOperationCompleted == null)) {
                this.ListarValoresPorFechaCancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarValoresPorFechaCancelacionOperationCompleted);
            }
            this.InvokeAsync("ListarValoresPorFechaCancelacion", new object[] {
                        fechaCancelacion,
                        tipo_deuda}, this.ListarValoresPorFechaCancelacionOperationCompleted, userState);
        }
        
        private void OnListarValoresPorFechaCancelacionOperationCompleted(object arg) {
            if ((this.ListarValoresPorFechaCancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarValoresPorFechaCancelacionCompleted(this, new ListarValoresPorFechaCancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.18.4.96/Servicios/Extractos.asmx/ListarValoresPorFechaConstitucion", RequestNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", ResponseNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Valor[] ListarValoresPorFechaConstitucion(System.DateTime fecConstitucion, string tipo_deuda) {
            object[] results = this.Invoke("ListarValoresPorFechaConstitucion", new object[] {
                        fecConstitucion,
                        tipo_deuda});
            return ((Valor[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarValoresPorFechaConstitucionAsync(System.DateTime fecConstitucion, string tipo_deuda) {
            this.ListarValoresPorFechaConstitucionAsync(fecConstitucion, tipo_deuda, null);
        }
        
        /// <remarks/>
        public void ListarValoresPorFechaConstitucionAsync(System.DateTime fecConstitucion, string tipo_deuda, object userState) {
            if ((this.ListarValoresPorFechaConstitucionOperationCompleted == null)) {
                this.ListarValoresPorFechaConstitucionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarValoresPorFechaConstitucionOperationCompleted);
            }
            this.InvokeAsync("ListarValoresPorFechaConstitucion", new object[] {
                        fecConstitucion,
                        tipo_deuda}, this.ListarValoresPorFechaConstitucionOperationCompleted, userState);
        }
        
        private void OnListarValoresPorFechaConstitucionOperationCompleted(object arg) {
            if ((this.ListarValoresPorFechaConstitucionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarValoresPorFechaConstitucionCompleted(this, new ListarValoresPorFechaConstitucionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.18.4.96/Servicios/Extractos.asmx/ListarValoresPorFechaValor", RequestNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", ResponseNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Valor[] ListarValoresPorFechaValor(System.DateTime fechaValor, string tipo_deuda) {
            object[] results = this.Invoke("ListarValoresPorFechaValor", new object[] {
                        fechaValor,
                        tipo_deuda});
            return ((Valor[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarValoresPorFechaValorAsync(System.DateTime fechaValor, string tipo_deuda) {
            this.ListarValoresPorFechaValorAsync(fechaValor, tipo_deuda, null);
        }
        
        /// <remarks/>
        public void ListarValoresPorFechaValorAsync(System.DateTime fechaValor, string tipo_deuda, object userState) {
            if ((this.ListarValoresPorFechaValorOperationCompleted == null)) {
                this.ListarValoresPorFechaValorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarValoresPorFechaValorOperationCompleted);
            }
            this.InvokeAsync("ListarValoresPorFechaValor", new object[] {
                        fechaValor,
                        tipo_deuda}, this.ListarValoresPorFechaValorOperationCompleted, userState);
        }
        
        private void OnListarValoresPorFechaValorOperationCompleted(object arg) {
            if ((this.ListarValoresPorFechaValorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarValoresPorFechaValorCompleted(this, new ListarValoresPorFechaValorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.18.4.96/Servicios/Extractos.asmx/ResumenSaldos", RequestNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", ResponseNamespace="http://172.18.4.96/Servicios/Extractos.asmx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Saldo[] ResumenSaldos(System.DateTime fechaLiquidacion, string tipo_deuda) {
            object[] results = this.Invoke("ResumenSaldos", new object[] {
                        fechaLiquidacion,
                        tipo_deuda});
            return ((Saldo[])(results[0]));
        }
        
        /// <remarks/>
        public void ResumenSaldosAsync(System.DateTime fechaLiquidacion, string tipo_deuda) {
            this.ResumenSaldosAsync(fechaLiquidacion, tipo_deuda, null);
        }
        
        /// <remarks/>
        public void ResumenSaldosAsync(System.DateTime fechaLiquidacion, string tipo_deuda, object userState) {
            if ((this.ResumenSaldosOperationCompleted == null)) {
                this.ResumenSaldosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResumenSaldosOperationCompleted);
            }
            this.InvokeAsync("ResumenSaldos", new object[] {
                        fechaLiquidacion,
                        tipo_deuda}, this.ResumenSaldosOperationCompleted, userState);
        }
        
        private void OnResumenSaldosOperationCompleted(object arg) {
            if ((this.ResumenSaldosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResumenSaldosCompleted(this, new ResumenSaldosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public partial class Cupon : ContratoDatos {
        
        private int numCuponField;
        
        private int numValorField;
        
        private string nemotecnicoField;
        
        private EEstado estadoField;
        
        private EMoneda codMonedaField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaVencimientoField;
        
        private System.DateTime fechaCancelacionField;
        
        private decimal interesBrutoField;
        
        private decimal interesNetoField;
        
        private decimal interesBrutoConvertidoField;
        
        private decimal interesNetoConvertidoField;
        
        private decimal interesNetoAcumuladoField;
        
        private decimal impuestoEfectivoField;
        
        private decimal impuestoVencidoField;
        
        private string codReferenciaField;
        
        private System.DateTime fechaConstitucionField;
        
        private TipoNegociacion tipoNegociacionField;
        
        private decimal impuestoTotalField;
        
        private decimal tasaBrutaField;
        
        private decimal tasaNetaField;
        
        private decimal interesBrutoEfectivoField;
        
        private string descripcionNegociacionField;
        
        /// <remarks/>
        public int NumCupon {
            get {
                return this.numCuponField;
            }
            set {
                this.numCuponField = value;
            }
        }
        
        /// <remarks/>
        public int NumValor {
            get {
                return this.numValorField;
            }
            set {
                this.numValorField = value;
            }
        }
        
        /// <remarks/>
        public string Nemotecnico {
            get {
                return this.nemotecnicoField;
            }
            set {
                this.nemotecnicoField = value;
            }
        }
        
        /// <remarks/>
        public EEstado Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public EMoneda CodMoneda {
            get {
                return this.codMonedaField;
            }
            set {
                this.codMonedaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCancelacion {
            get {
                return this.fechaCancelacionField;
            }
            set {
                this.fechaCancelacionField = value;
            }
        }
        
        /// <remarks/>
        public decimal InteresBruto {
            get {
                return this.interesBrutoField;
            }
            set {
                this.interesBrutoField = value;
            }
        }
        
        /// <remarks/>
        public decimal InteresNeto {
            get {
                return this.interesNetoField;
            }
            set {
                this.interesNetoField = value;
            }
        }
        
        /// <remarks/>
        public decimal InteresBrutoConvertido {
            get {
                return this.interesBrutoConvertidoField;
            }
            set {
                this.interesBrutoConvertidoField = value;
            }
        }
        
        /// <remarks/>
        public decimal InteresNetoConvertido {
            get {
                return this.interesNetoConvertidoField;
            }
            set {
                this.interesNetoConvertidoField = value;
            }
        }
        
        /// <remarks/>
        public decimal InteresNetoAcumulado {
            get {
                return this.interesNetoAcumuladoField;
            }
            set {
                this.interesNetoAcumuladoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ImpuestoEfectivo {
            get {
                return this.impuestoEfectivoField;
            }
            set {
                this.impuestoEfectivoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ImpuestoVencido {
            get {
                return this.impuestoVencidoField;
            }
            set {
                this.impuestoVencidoField = value;
            }
        }
        
        /// <remarks/>
        public string CodReferencia {
            get {
                return this.codReferenciaField;
            }
            set {
                this.codReferenciaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaConstitucion {
            get {
                return this.fechaConstitucionField;
            }
            set {
                this.fechaConstitucionField = value;
            }
        }
        
        /// <remarks/>
        public TipoNegociacion TipoNegociacion {
            get {
                return this.tipoNegociacionField;
            }
            set {
                this.tipoNegociacionField = value;
            }
        }
        
        /// <remarks/>
        public decimal ImpuestoTotal {
            get {
                return this.impuestoTotalField;
            }
            set {
                this.impuestoTotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal TasaBruta {
            get {
                return this.tasaBrutaField;
            }
            set {
                this.tasaBrutaField = value;
            }
        }
        
        /// <remarks/>
        public decimal TasaNeta {
            get {
                return this.tasaNetaField;
            }
            set {
                this.tasaNetaField = value;
            }
        }
        
        /// <remarks/>
        public decimal InteresBrutoEfectivo {
            get {
                return this.interesBrutoEfectivoField;
            }
            set {
                this.interesBrutoEfectivoField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionNegociacion {
            get {
                return this.descripcionNegociacionField;
            }
            set {
                this.descripcionNegociacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public enum EEstado {
        
        /// <remarks/>
        Ninguno = 1,
        
        /// <remarks/>
        Guardada = 2,
        
        /// <remarks/>
        Aprobada = 4,
        
        /// <remarks/>
        Eliminada = 8,
        
        /// <remarks/>
        PorConfirmar = 16,
        
        /// <remarks/>
        Vigente = 32,
        
        /// <remarks/>
        Prescrita = 64,
        
        /// <remarks/>
        Anulada = 128,
        
        /// <remarks/>
        EnCobro = 256,
        
        /// <remarks/>
        CanceladaAnticipada = 512,
        
        /// <remarks/>
        Cancelada = 1024,
        
        /// <remarks/>
        AnulacionXAprobar = 2048,
        
        /// <remarks/>
        InteresPrescrito = 4096,
        
        /// <remarks/>
        EnEdicion = 8192,
        
        /// <remarks/>
        Rechazado = 16384,
        
        /// <remarks/>
        AnuladoPorCanje = 32768,
        
        /// <remarks/>
        AnuladoPorRedencion = 65536,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public enum EMoneda {
        
        /// <remarks/>
        Ninguna,
        
        /// <remarks/>
        Colones,
        
        /// <remarks/>
        Dolares,
        
        /// <remarks/>
        Euros,
        
        /// <remarks/>
        UnidadesDeDesarrollo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public enum TipoNegociacion {
        
        /// <remarks/>
        Ninguno,
        
        /// <remarks/>
        Compra,
        
        /// <remarks/>
        Venta,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstadoCuenta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EstadoCuentaDiario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Movimiento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cuenta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestaObtenerMisCuentas))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SaldoCierreDiario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Filtro))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Valor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Saldo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cupon))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public partial class ContratoDatos {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/ACS")]
    public partial class EstadoCuenta : ContratoDatos {
        
        private EstadoCuentaDiario[] estadosCuentaDiariosField;
        
        private System.DateTime fecInicioField;
        
        private System.DateTime fecFinalField;
        
        private Moneda codMonedaField;
        
        private short codEntidadPropietariaField;
        
        private string cuentaSINPEField;
        
        /// <remarks/>
        public EstadoCuentaDiario[] EstadosCuentaDiarios {
            get {
                return this.estadosCuentaDiariosField;
            }
            set {
                this.estadosCuentaDiariosField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FecInicio {
            get {
                return this.fecInicioField;
            }
            set {
                this.fecInicioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FecFinal {
            get {
                return this.fecFinalField;
            }
            set {
                this.fecFinalField = value;
            }
        }
        
        /// <remarks/>
        public Moneda CodMoneda {
            get {
                return this.codMonedaField;
            }
            set {
                this.codMonedaField = value;
            }
        }
        
        /// <remarks/>
        public short CodEntidadPropietaria {
            get {
                return this.codEntidadPropietariaField;
            }
            set {
                this.codEntidadPropietariaField = value;
            }
        }
        
        /// <remarks/>
        public string CuentaSINPE {
            get {
                return this.cuentaSINPEField;
            }
            set {
                this.cuentaSINPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/ACS")]
    public partial class EstadoCuentaDiario : ContratoDatos {
        
        private decimal saldoInicialRetenidoField;
        
        private decimal saldoFinalRetenidoField;
        
        private Movimiento[] movimientosField;
        
        private decimal saldoInicialField;
        
        private decimal saldoFinalField;
        
        private System.DateTime fechaField;
        
        /// <remarks/>
        public decimal SaldoInicialRetenido {
            get {
                return this.saldoInicialRetenidoField;
            }
            set {
                this.saldoInicialRetenidoField = value;
            }
        }
        
        /// <remarks/>
        public decimal SaldoFinalRetenido {
            get {
                return this.saldoFinalRetenidoField;
            }
            set {
                this.saldoFinalRetenidoField = value;
            }
        }
        
        /// <remarks/>
        public Movimiento[] Movimientos {
            get {
                return this.movimientosField;
            }
            set {
                this.movimientosField = value;
            }
        }
        
        /// <remarks/>
        public decimal SaldoInicial {
            get {
                return this.saldoInicialField;
            }
            set {
                this.saldoInicialField = value;
            }
        }
        
        /// <remarks/>
        public decimal SaldoFinal {
            get {
                return this.saldoFinalField;
            }
            set {
                this.saldoFinalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/ACS")]
    public partial class Movimiento : ContratoDatos {
        
        private System.DateTime fechaField;
        
        private decimal montoField;
        
        private string referenciaField;
        
        private short codServicioField;
        
        private string descripcionField;
        
        private TipoMovimiento tipoField;
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string Referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        public short CodServicio {
            get {
                return this.codServicioField;
            }
            set {
                this.codServicioField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public TipoMovimiento Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/ACS")]
    public enum TipoMovimiento {
        
        /// <remarks/>
        Credito,
        
        /// <remarks/>
        Debito,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/ACS")]
    public enum Moneda {
        
        /// <remarks/>
        Ninguno,
        
        /// <remarks/>
        Colones,
        
        /// <remarks/>
        Dolares,
        
        /// <remarks/>
        Euros,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/ACS")]
    public partial class Cuenta : ContratoDatos {
        
        private string numeroField;
        
        private string nombreField;
        
        private string codigoDeMonedaField;
        
        private string estadoField;
        
        private string numeroIbanField;
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoDeMoneda {
            get {
                return this.codigoDeMonedaField;
            }
            set {
                this.codigoDeMonedaField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroIban {
            get {
                return this.numeroIbanField;
            }
            set {
                this.numeroIbanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/ACS")]
    public partial class RespuestaObtenerMisCuentas : ContratoDatos {
        
        private bool consultaSePudoRealizarField;
        
        private string[] erroresDeValidacionField;
        
        private Cuenta[] misCuentasField;
        
        /// <remarks/>
        public bool ConsultaSePudoRealizar {
            get {
                return this.consultaSePudoRealizarField;
            }
            set {
                this.consultaSePudoRealizarField = value;
            }
        }
        
        /// <remarks/>
        public string[] ErroresDeValidacion {
            get {
                return this.erroresDeValidacionField;
            }
            set {
                this.erroresDeValidacionField = value;
            }
        }
        
        /// <remarks/>
        public Cuenta[] MisCuentas {
            get {
                return this.misCuentasField;
            }
            set {
                this.misCuentasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/ACS")]
    public partial class SaldoCierreDiario : ContratoDatos {
        
        private Moneda codMonedaField;
        
        private decimal saldoEncajeField;
        
        private decimal saldoField;
        
        private decimal montoRetenidoField;
        
        private decimal saldoRealField;
        
        private System.DateTime fechaField;
        
        /// <remarks/>
        public Moneda CodMoneda {
            get {
                return this.codMonedaField;
            }
            set {
                this.codMonedaField = value;
            }
        }
        
        /// <remarks/>
        public decimal SaldoEncaje {
            get {
                return this.saldoEncajeField;
            }
            set {
                this.saldoEncajeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
        
        /// <remarks/>
        public decimal MontoRetenido {
            get {
                return this.montoRetenidoField;
            }
            set {
                this.montoRetenidoField = value;
            }
        }
        
        /// <remarks/>
        public decimal SaldoReal {
            get {
                return this.saldoRealField;
            }
            set {
                this.saldoRealField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/ACS")]
    public partial class Filtro : ContratoDatos {
        
        private System.DateTime fecInicioField;
        
        private System.DateTime fecFinalField;
        
        private string cuentaSINPEField;
        
        private short codEntidadField;
        
        /// <remarks/>
        public System.DateTime FecInicio {
            get {
                return this.fecInicioField;
            }
            set {
                this.fecInicioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FecFinal {
            get {
                return this.fecFinalField;
            }
            set {
                this.fecFinalField = value;
            }
        }
        
        /// <remarks/>
        public string CuentaSINPE {
            get {
                return this.cuentaSINPEField;
            }
            set {
                this.cuentaSINPEField = value;
            }
        }
        
        /// <remarks/>
        public short CodEntidad {
            get {
                return this.codEntidadField;
            }
            set {
                this.codEntidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public partial class Valor : ContratoDatos {
        
        private int numValorField;
        
        private string nemotecnicoField;
        
        private EEstado estadoField;
        
        private System.DateTime fechaValorField;
        
        private System.DateTime fechaCancelacionField;
        
        private EMoneda codMonedaField;
        
        private System.DateTime fecVencimientoField;
        
        private decimal valorFacialField;
        
        private decimal valorTransadoNetoField;
        
        private decimal valorTransadoBrutoField;
        
        private decimal interesNetoAcumuladoField;
        
        private decimal impuestoPagadoField;
        
        private decimal rendimientoPorDescuentoField;
        
        private decimal precioField;
        
        private decimal premioField;
        
        private decimal descuentoField;
        
        private string codReferenciaField;
        
        private System.DateTime fechaConstitucionField;
        
        private TipoNegociacion tipoNegociacionField;
        
        private TipoValor tipoValorField;
        
        private decimal plazoValorField;
        
        private decimal tasaBrutaField;
        
        private decimal tasaNetaField;
        
        private SistemaNegociacion sistemaNegociacionField;
        
        private string motivoAnulacionField;
        
        private string numeroEmisionSerieField;
        
        private string numeroSerieField;
        
        private decimal margenField;
        
        private string propietarioField;
        
        private string descripcionNegociacionField;
        
        private string numeroIdentificacionField;
        
        private TipoIdentificacion tipoIdentificacionField;
        
        /// <remarks/>
        public int NumValor {
            get {
                return this.numValorField;
            }
            set {
                this.numValorField = value;
            }
        }
        
        /// <remarks/>
        public string Nemotecnico {
            get {
                return this.nemotecnicoField;
            }
            set {
                this.nemotecnicoField = value;
            }
        }
        
        /// <remarks/>
        public EEstado Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaValor {
            get {
                return this.fechaValorField;
            }
            set {
                this.fechaValorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCancelacion {
            get {
                return this.fechaCancelacionField;
            }
            set {
                this.fechaCancelacionField = value;
            }
        }
        
        /// <remarks/>
        public EMoneda CodMoneda {
            get {
                return this.codMonedaField;
            }
            set {
                this.codMonedaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FecVencimiento {
            get {
                return this.fecVencimientoField;
            }
            set {
                this.fecVencimientoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorFacial {
            get {
                return this.valorFacialField;
            }
            set {
                this.valorFacialField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorTransadoNeto {
            get {
                return this.valorTransadoNetoField;
            }
            set {
                this.valorTransadoNetoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorTransadoBruto {
            get {
                return this.valorTransadoBrutoField;
            }
            set {
                this.valorTransadoBrutoField = value;
            }
        }
        
        /// <remarks/>
        public decimal InteresNetoAcumulado {
            get {
                return this.interesNetoAcumuladoField;
            }
            set {
                this.interesNetoAcumuladoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ImpuestoPagado {
            get {
                return this.impuestoPagadoField;
            }
            set {
                this.impuestoPagadoField = value;
            }
        }
        
        /// <remarks/>
        public decimal RendimientoPorDescuento {
            get {
                return this.rendimientoPorDescuentoField;
            }
            set {
                this.rendimientoPorDescuentoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        /// <remarks/>
        public decimal Premio {
            get {
                return this.premioField;
            }
            set {
                this.premioField = value;
            }
        }
        
        /// <remarks/>
        public decimal Descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
            }
        }
        
        /// <remarks/>
        public string CodReferencia {
            get {
                return this.codReferenciaField;
            }
            set {
                this.codReferenciaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaConstitucion {
            get {
                return this.fechaConstitucionField;
            }
            set {
                this.fechaConstitucionField = value;
            }
        }
        
        /// <remarks/>
        public TipoNegociacion TipoNegociacion {
            get {
                return this.tipoNegociacionField;
            }
            set {
                this.tipoNegociacionField = value;
            }
        }
        
        /// <remarks/>
        public TipoValor TipoValor {
            get {
                return this.tipoValorField;
            }
            set {
                this.tipoValorField = value;
            }
        }
        
        /// <remarks/>
        public decimal PlazoValor {
            get {
                return this.plazoValorField;
            }
            set {
                this.plazoValorField = value;
            }
        }
        
        /// <remarks/>
        public decimal TasaBruta {
            get {
                return this.tasaBrutaField;
            }
            set {
                this.tasaBrutaField = value;
            }
        }
        
        /// <remarks/>
        public decimal TasaNeta {
            get {
                return this.tasaNetaField;
            }
            set {
                this.tasaNetaField = value;
            }
        }
        
        /// <remarks/>
        public SistemaNegociacion SistemaNegociacion {
            get {
                return this.sistemaNegociacionField;
            }
            set {
                this.sistemaNegociacionField = value;
            }
        }
        
        /// <remarks/>
        public string MotivoAnulacion {
            get {
                return this.motivoAnulacionField;
            }
            set {
                this.motivoAnulacionField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroEmisionSerie {
            get {
                return this.numeroEmisionSerieField;
            }
            set {
                this.numeroEmisionSerieField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
            }
        }
        
        /// <remarks/>
        public decimal Margen {
            get {
                return this.margenField;
            }
            set {
                this.margenField = value;
            }
        }
        
        /// <remarks/>
        public string Propietario {
            get {
                return this.propietarioField;
            }
            set {
                this.propietarioField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionNegociacion {
            get {
                return this.descripcionNegociacionField;
            }
            set {
                this.descripcionNegociacionField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroIdentificacion {
            get {
                return this.numeroIdentificacionField;
            }
            set {
                this.numeroIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        public TipoIdentificacion TipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public enum TipoValor {
        
        /// <remarks/>
        Ninguno,
        
        /// <remarks/>
        CeroCupon,
        
        /// <remarks/>
        CuponTasaFija,
        
        /// <remarks/>
        CuponTasaVariable,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public enum SistemaNegociacion {
        
        /// <remarks/>
        Ninguno,
        
        /// <remarks/>
        VentaDirecta,
        
        /// <remarks/>
        SistemaColocacionEmisiones,
        
        /// <remarks/>
        Ventanilla,
        
        /// <remarks/>
        Subasta,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public enum TipoIdentificacion {
        
        /// <remarks/>
        OtroTipoId,
        
        /// <remarks/>
        CedulaIdentidad,
        
        /// <remarks/>
        CedulaResidencia,
        
        /// <remarks/>
        NumeroDeSerie,
        
        /// <remarks/>
        CedulaJuridica,
        
        /// <remarks/>
        GobiernoCentral,
        
        /// <remarks/>
        InstitucionAutonoma,
        
        /// <remarks/>
        ExtranjeroNoResidente,
        
        /// <remarks/>
        NumeroUnicoIdentificacionDIMEX,
        
        /// <remarks/>
        ProcesosDeAmnistia,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public partial class Saldo : ContratoDatos {
        
        private TipoSaldoRds codTipoSaldoField;
        
        private TipoPlazoRds tipoPlazoField;
        
        private System.DateTime fechaSaldoField;
        
        private string instrumentoField;
        
        private EMoneda codMonedaField;
        
        private decimal principalField;
        
        private decimal ejercicioAnteriorField;
        
        private decimal ejercicioCorrienteField;
        
        /// <remarks/>
        public TipoSaldoRds CodTipoSaldo {
            get {
                return this.codTipoSaldoField;
            }
            set {
                this.codTipoSaldoField = value;
            }
        }
        
        /// <remarks/>
        public TipoPlazoRds TipoPlazo {
            get {
                return this.tipoPlazoField;
            }
            set {
                this.tipoPlazoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaSaldo {
            get {
                return this.fechaSaldoField;
            }
            set {
                this.fechaSaldoField = value;
            }
        }
        
        /// <remarks/>
        public string Instrumento {
            get {
                return this.instrumentoField;
            }
            set {
                this.instrumentoField = value;
            }
        }
        
        /// <remarks/>
        public EMoneda CodMoneda {
            get {
                return this.codMonedaField;
            }
            set {
                this.codMonedaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <remarks/>
        public decimal EjercicioAnterior {
            get {
                return this.ejercicioAnteriorField;
            }
            set {
                this.ejercicioAnteriorField = value;
            }
        }
        
        /// <remarks/>
        public decimal EjercicioCorriente {
            get {
                return this.ejercicioCorrienteField;
            }
            set {
                this.ejercicioCorrienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public enum TipoSaldoRds {
        
        /// <remarks/>
        Ninguno,
        
        /// <remarks/>
        Principal,
        
        /// <remarks/>
        RendimientoDescuento,
        
        /// <remarks/>
        Descuento,
        
        /// <remarks/>
        Premio,
        
        /// <remarks/>
        InteresAcumulado,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sinpe.cr/webservices/Rds")]
    public enum TipoPlazoRds {
        
        /// <remarks/>
        MuyCortoPlazo,
        
        /// <remarks/>
        CortoPlazo,
        
        /// <remarks/>
        MedianoPlazo,
        
        /// <remarks/>
        LargoPlazo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarCuponesPorFechaCancelacionCompletedEventHandler(object sender, ListarCuponesPorFechaCancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCuponesPorFechaCancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCuponesPorFechaCancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cupon[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cupon[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarCuponesPorFechaConstitucionCompletedEventHandler(object sender, ListarCuponesPorFechaConstitucionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCuponesPorFechaConstitucionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCuponesPorFechaConstitucionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cupon[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cupon[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarCuponesPorFechaValorCompletedEventHandler(object sender, ListarCuponesPorFechaValorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCuponesPorFechaValorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCuponesPorFechaValorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cupon[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cupon[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarValoresPorFechaCancelacionCompletedEventHandler(object sender, ListarValoresPorFechaCancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarValoresPorFechaCancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarValoresPorFechaCancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Valor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Valor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarValoresPorFechaConstitucionCompletedEventHandler(object sender, ListarValoresPorFechaConstitucionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarValoresPorFechaConstitucionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarValoresPorFechaConstitucionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Valor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Valor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListarValoresPorFechaValorCompletedEventHandler(object sender, ListarValoresPorFechaValorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarValoresPorFechaValorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarValoresPorFechaValorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Valor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Valor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ResumenSaldosCompletedEventHandler(object sender, ResumenSaldosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResumenSaldosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResumenSaldosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Saldo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Saldo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591