//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.sr_rdi_rde {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCupon", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", ItemName="Cupon")]
    [System.SerializableAttribute()]
    public class ArrayOfCupon : System.Collections.Generic.List<LogicaNegocio.sr_rdi_rde.Cupon> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfValor", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", ItemName="Valor")]
    [System.SerializableAttribute()]
    public class ArrayOfValor : System.Collections.Generic.List<LogicaNegocio.sr_rdi_rde.Valor> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSaldo", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", ItemName="Saldo")]
    [System.SerializableAttribute()]
    public class ArrayOfSaldo : System.Collections.Generic.List<LogicaNegocio.sr_rdi_rde.Saldo> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", ConfigurationName="sr_rdi_rde.ExtractosSoap")]
    public interface ExtractosSoap {
        
        // CODEGEN: Generating message contract since element name tipo_deuda from namespace http://172.18.4.96/Servicios/Extractos.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarCuponesPorFechaCancelacion", ReplyAction="*")]
        Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionResponse ListarCuponesPorFechaCancelacion(Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarCuponesPorFechaCancelacion", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionResponse> ListarCuponesPorFechaCancelacionAsync(Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequest request);
        
        // CODEGEN: Generating message contract since element name tipo_deuda from namespace http://172.18.4.96/Servicios/Extractos.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarCuponesPorFechaConstitucion", ReplyAction="*")]
        Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionResponse ListarCuponesPorFechaConstitucion(Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarCuponesPorFechaConstitucion", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionResponse> ListarCuponesPorFechaConstitucionAsync(Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequest request);
        
        // CODEGEN: Generating message contract since element name tipo_deuda from namespace http://172.18.4.96/Servicios/Extractos.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarCuponesPorFechaValor", ReplyAction="*")]
        Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorResponse ListarCuponesPorFechaValor(Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarCuponesPorFechaValor", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorResponse> ListarCuponesPorFechaValorAsync(Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequest request);
        
        // CODEGEN: Generating message contract since element name tipo_deuda from namespace http://172.18.4.96/Servicios/Extractos.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarValoresPorFechaCancelacion", ReplyAction="*")]
        Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionResponse ListarValoresPorFechaCancelacion(Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarValoresPorFechaCancelacion", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionResponse> ListarValoresPorFechaCancelacionAsync(Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequest request);
        
        // CODEGEN: Generating message contract since element name tipo_deuda from namespace http://172.18.4.96/Servicios/Extractos.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarValoresPorFechaConstitucion", ReplyAction="*")]
        Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionResponse ListarValoresPorFechaConstitucion(Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarValoresPorFechaConstitucion", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionResponse> ListarValoresPorFechaConstitucionAsync(Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequest request);
        
        // CODEGEN: Generating message contract since element name tipo_deuda from namespace http://172.18.4.96/Servicios/Extractos.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarValoresPorFechaValor", ReplyAction="*")]
        Presentacion.sr_rdi_rde.ListarValoresPorFechaValorResponse ListarValoresPorFechaValor(Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ListarValoresPorFechaValor", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarValoresPorFechaValorResponse> ListarValoresPorFechaValorAsync(Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequest request);
        
        // CODEGEN: Generating message contract since element name tipo_deuda from namespace http://172.18.4.96/Servicios/Extractos.asmx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ResumenSaldos", ReplyAction="*")]
        Presentacion.sr_rdi_rde.ResumenSaldosResponse ResumenSaldos(Presentacion.sr_rdi_rde.ResumenSaldosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://172.18.4.96/Servicios/Extractos.asmx/ResumenSaldos", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ResumenSaldosResponse> ResumenSaldosAsync(Presentacion.sr_rdi_rde.ResumenSaldosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCuponesPorFechaCancelacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCuponesPorFechaCancelacion", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequestBody Body;
        
        public ListarCuponesPorFechaCancelacionRequest() {
        }
        
        public ListarCuponesPorFechaCancelacionRequest(Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarCuponesPorFechaCancelacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fechaCancelacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo_deuda;
        
        public ListarCuponesPorFechaCancelacionRequestBody() {
        }
        
        public ListarCuponesPorFechaCancelacionRequestBody(System.DateTime fechaCancelacion, string tipo_deuda) {
            this.fechaCancelacion = fechaCancelacion;
            this.tipo_deuda = tipo_deuda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCuponesPorFechaCancelacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCuponesPorFechaCancelacionResponse", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionResponseBody Body;
        
        public ListarCuponesPorFechaCancelacionResponse() {
        }
        
        public ListarCuponesPorFechaCancelacionResponse(Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarCuponesPorFechaCancelacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentacion.sr_rdi_rde.ArrayOfCupon ListarCuponesPorFechaCancelacionResult;
        
        public ListarCuponesPorFechaCancelacionResponseBody() {
        }
        
        public ListarCuponesPorFechaCancelacionResponseBody(Presentacion.sr_rdi_rde.ArrayOfCupon ListarCuponesPorFechaCancelacionResult) {
            this.ListarCuponesPorFechaCancelacionResult = ListarCuponesPorFechaCancelacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCuponesPorFechaConstitucionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCuponesPorFechaConstitucion", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequestBody Body;
        
        public ListarCuponesPorFechaConstitucionRequest() {
        }
        
        public ListarCuponesPorFechaConstitucionRequest(Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarCuponesPorFechaConstitucionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fecConstitucion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo_deuda;
        
        public ListarCuponesPorFechaConstitucionRequestBody() {
        }
        
        public ListarCuponesPorFechaConstitucionRequestBody(System.DateTime fecConstitucion, string tipo_deuda) {
            this.fecConstitucion = fecConstitucion;
            this.tipo_deuda = tipo_deuda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCuponesPorFechaConstitucionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCuponesPorFechaConstitucionResponse", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionResponseBody Body;
        
        public ListarCuponesPorFechaConstitucionResponse() {
        }
        
        public ListarCuponesPorFechaConstitucionResponse(Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarCuponesPorFechaConstitucionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentacion.sr_rdi_rde.ArrayOfCupon ListarCuponesPorFechaConstitucionResult;
        
        public ListarCuponesPorFechaConstitucionResponseBody() {
        }
        
        public ListarCuponesPorFechaConstitucionResponseBody(Presentacion.sr_rdi_rde.ArrayOfCupon ListarCuponesPorFechaConstitucionResult) {
            this.ListarCuponesPorFechaConstitucionResult = ListarCuponesPorFechaConstitucionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCuponesPorFechaValorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCuponesPorFechaValor", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequestBody Body;
        
        public ListarCuponesPorFechaValorRequest() {
        }
        
        public ListarCuponesPorFechaValorRequest(Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarCuponesPorFechaValorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fechaValor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo_deuda;
        
        public ListarCuponesPorFechaValorRequestBody() {
        }
        
        public ListarCuponesPorFechaValorRequestBody(System.DateTime fechaValor, string tipo_deuda) {
            this.fechaValor = fechaValor;
            this.tipo_deuda = tipo_deuda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCuponesPorFechaValorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCuponesPorFechaValorResponse", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorResponseBody Body;
        
        public ListarCuponesPorFechaValorResponse() {
        }
        
        public ListarCuponesPorFechaValorResponse(Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarCuponesPorFechaValorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentacion.sr_rdi_rde.ArrayOfCupon ListarCuponesPorFechaValorResult;
        
        public ListarCuponesPorFechaValorResponseBody() {
        }
        
        public ListarCuponesPorFechaValorResponseBody(Presentacion.sr_rdi_rde.ArrayOfCupon ListarCuponesPorFechaValorResult) {
            this.ListarCuponesPorFechaValorResult = ListarCuponesPorFechaValorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarValoresPorFechaCancelacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarValoresPorFechaCancelacion", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequestBody Body;
        
        public ListarValoresPorFechaCancelacionRequest() {
        }
        
        public ListarValoresPorFechaCancelacionRequest(Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarValoresPorFechaCancelacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fechaCancelacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo_deuda;
        
        public ListarValoresPorFechaCancelacionRequestBody() {
        }
        
        public ListarValoresPorFechaCancelacionRequestBody(System.DateTime fechaCancelacion, string tipo_deuda) {
            this.fechaCancelacion = fechaCancelacion;
            this.tipo_deuda = tipo_deuda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarValoresPorFechaCancelacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarValoresPorFechaCancelacionResponse", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionResponseBody Body;
        
        public ListarValoresPorFechaCancelacionResponse() {
        }
        
        public ListarValoresPorFechaCancelacionResponse(Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarValoresPorFechaCancelacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentacion.sr_rdi_rde.ArrayOfValor ListarValoresPorFechaCancelacionResult;
        
        public ListarValoresPorFechaCancelacionResponseBody() {
        }
        
        public ListarValoresPorFechaCancelacionResponseBody(Presentacion.sr_rdi_rde.ArrayOfValor ListarValoresPorFechaCancelacionResult) {
            this.ListarValoresPorFechaCancelacionResult = ListarValoresPorFechaCancelacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarValoresPorFechaConstitucionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarValoresPorFechaConstitucion", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequestBody Body;
        
        public ListarValoresPorFechaConstitucionRequest() {
        }
        
        public ListarValoresPorFechaConstitucionRequest(Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarValoresPorFechaConstitucionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fecConstitucion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo_deuda;
        
        public ListarValoresPorFechaConstitucionRequestBody() {
        }
        
        public ListarValoresPorFechaConstitucionRequestBody(System.DateTime fecConstitucion, string tipo_deuda) {
            this.fecConstitucion = fecConstitucion;
            this.tipo_deuda = tipo_deuda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarValoresPorFechaConstitucionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarValoresPorFechaConstitucionResponse", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionResponseBody Body;
        
        public ListarValoresPorFechaConstitucionResponse() {
        }
        
        public ListarValoresPorFechaConstitucionResponse(Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarValoresPorFechaConstitucionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentacion.sr_rdi_rde.ArrayOfValor ListarValoresPorFechaConstitucionResult;
        
        public ListarValoresPorFechaConstitucionResponseBody() {
        }
        
        public ListarValoresPorFechaConstitucionResponseBody(Presentacion.sr_rdi_rde.ArrayOfValor ListarValoresPorFechaConstitucionResult) {
            this.ListarValoresPorFechaConstitucionResult = ListarValoresPorFechaConstitucionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarValoresPorFechaValorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarValoresPorFechaValor", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequestBody Body;
        
        public ListarValoresPorFechaValorRequest() {
        }
        
        public ListarValoresPorFechaValorRequest(Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarValoresPorFechaValorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fechaValor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo_deuda;
        
        public ListarValoresPorFechaValorRequestBody() {
        }
        
        public ListarValoresPorFechaValorRequestBody(System.DateTime fechaValor, string tipo_deuda) {
            this.fechaValor = fechaValor;
            this.tipo_deuda = tipo_deuda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarValoresPorFechaValorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarValoresPorFechaValorResponse", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ListarValoresPorFechaValorResponseBody Body;
        
        public ListarValoresPorFechaValorResponse() {
        }
        
        public ListarValoresPorFechaValorResponse(Presentacion.sr_rdi_rde.ListarValoresPorFechaValorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ListarValoresPorFechaValorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentacion.sr_rdi_rde.ArrayOfValor ListarValoresPorFechaValorResult;
        
        public ListarValoresPorFechaValorResponseBody() {
        }
        
        public ListarValoresPorFechaValorResponseBody(Presentacion.sr_rdi_rde.ArrayOfValor ListarValoresPorFechaValorResult) {
            this.ListarValoresPorFechaValorResult = ListarValoresPorFechaValorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResumenSaldosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResumenSaldos", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ResumenSaldosRequestBody Body;
        
        public ResumenSaldosRequest() {
        }
        
        public ResumenSaldosRequest(Presentacion.sr_rdi_rde.ResumenSaldosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ResumenSaldosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fechaLiquidacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo_deuda;
        
        public ResumenSaldosRequestBody() {
        }
        
        public ResumenSaldosRequestBody(System.DateTime fechaLiquidacion, string tipo_deuda) {
            this.fechaLiquidacion = fechaLiquidacion;
            this.tipo_deuda = tipo_deuda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResumenSaldosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResumenSaldosResponse", Namespace="http://172.18.4.96/Servicios/Extractos.asmx/", Order=0)]
        public Presentacion.sr_rdi_rde.ResumenSaldosResponseBody Body;
        
        public ResumenSaldosResponse() {
        }
        
        public ResumenSaldosResponse(Presentacion.sr_rdi_rde.ResumenSaldosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://172.18.4.96/Servicios/Extractos.asmx/")]
    public partial class ResumenSaldosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presentacion.sr_rdi_rde.ArrayOfSaldo ResumenSaldosResult;
        
        public ResumenSaldosResponseBody() {
        }
        
        public ResumenSaldosResponseBody(Presentacion.sr_rdi_rde.ArrayOfSaldo ResumenSaldosResult) {
            this.ResumenSaldosResult = ResumenSaldosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExtractosSoapChannel : Presentacion.sr_rdi_rde.ExtractosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExtractosSoapClient : System.ServiceModel.ClientBase<Presentacion.sr_rdi_rde.ExtractosSoap>, Presentacion.sr_rdi_rde.ExtractosSoap {
        
        public ExtractosSoapClient() {
        }
        
        public ExtractosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExtractosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtractosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtractosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionResponse Presentacion.sr_rdi_rde.ExtractosSoap.ListarCuponesPorFechaCancelacion(Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequest request) {
            return base.Channel.ListarCuponesPorFechaCancelacion(request);
        }
        
        public Presentacion.sr_rdi_rde.ArrayOfCupon ListarCuponesPorFechaCancelacion(System.DateTime fechaCancelacion, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequest inValue = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequestBody();
            inValue.Body.fechaCancelacion = fechaCancelacion;
            inValue.Body.tipo_deuda = tipo_deuda;
            Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionResponse retVal = ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarCuponesPorFechaCancelacion(inValue);
            return retVal.Body.ListarCuponesPorFechaCancelacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionResponse> Presentacion.sr_rdi_rde.ExtractosSoap.ListarCuponesPorFechaCancelacionAsync(Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequest request) {
            return base.Channel.ListarCuponesPorFechaCancelacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionResponse> ListarCuponesPorFechaCancelacionAsync(System.DateTime fechaCancelacion, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequest inValue = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaCancelacionRequestBody();
            inValue.Body.fechaCancelacion = fechaCancelacion;
            inValue.Body.tipo_deuda = tipo_deuda;
            return ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarCuponesPorFechaCancelacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionResponse Presentacion.sr_rdi_rde.ExtractosSoap.ListarCuponesPorFechaConstitucion(Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequest request) {
            return base.Channel.ListarCuponesPorFechaConstitucion(request);
        }
        
        public Presentacion.sr_rdi_rde.ArrayOfCupon ListarCuponesPorFechaConstitucion(System.DateTime fecConstitucion, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequest inValue = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequestBody();
            inValue.Body.fecConstitucion = fecConstitucion;
            inValue.Body.tipo_deuda = tipo_deuda;
            Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionResponse retVal = ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarCuponesPorFechaConstitucion(inValue);
            return retVal.Body.ListarCuponesPorFechaConstitucionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionResponse> Presentacion.sr_rdi_rde.ExtractosSoap.ListarCuponesPorFechaConstitucionAsync(Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequest request) {
            return base.Channel.ListarCuponesPorFechaConstitucionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionResponse> ListarCuponesPorFechaConstitucionAsync(System.DateTime fecConstitucion, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequest inValue = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaConstitucionRequestBody();
            inValue.Body.fecConstitucion = fecConstitucion;
            inValue.Body.tipo_deuda = tipo_deuda;
            return ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarCuponesPorFechaConstitucionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorResponse Presentacion.sr_rdi_rde.ExtractosSoap.ListarCuponesPorFechaValor(Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequest request) {
            return base.Channel.ListarCuponesPorFechaValor(request);
        }
        
        public Presentacion.sr_rdi_rde.ArrayOfCupon ListarCuponesPorFechaValor(System.DateTime fechaValor, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequest inValue = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequestBody();
            inValue.Body.fechaValor = fechaValor;
            inValue.Body.tipo_deuda = tipo_deuda;
            Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorResponse retVal = ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarCuponesPorFechaValor(inValue);
            return retVal.Body.ListarCuponesPorFechaValorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorResponse> Presentacion.sr_rdi_rde.ExtractosSoap.ListarCuponesPorFechaValorAsync(Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequest request) {
            return base.Channel.ListarCuponesPorFechaValorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorResponse> ListarCuponesPorFechaValorAsync(System.DateTime fechaValor, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequest inValue = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarCuponesPorFechaValorRequestBody();
            inValue.Body.fechaValor = fechaValor;
            inValue.Body.tipo_deuda = tipo_deuda;
            return ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarCuponesPorFechaValorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionResponse Presentacion.sr_rdi_rde.ExtractosSoap.ListarValoresPorFechaCancelacion(Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequest request) {
            return base.Channel.ListarValoresPorFechaCancelacion(request);
        }
        
        public Presentacion.sr_rdi_rde.ArrayOfValor ListarValoresPorFechaCancelacion(System.DateTime fechaCancelacion, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequest inValue = new Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequestBody();
            inValue.Body.fechaCancelacion = fechaCancelacion;
            inValue.Body.tipo_deuda = tipo_deuda;
            Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionResponse retVal = ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarValoresPorFechaCancelacion(inValue);
            return retVal.Body.ListarValoresPorFechaCancelacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionResponse> Presentacion.sr_rdi_rde.ExtractosSoap.ListarValoresPorFechaCancelacionAsync(Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequest request) {
            return base.Channel.ListarValoresPorFechaCancelacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionResponse> ListarValoresPorFechaCancelacionAsync(System.DateTime fechaCancelacion, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequest inValue = new Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarValoresPorFechaCancelacionRequestBody();
            inValue.Body.fechaCancelacion = fechaCancelacion;
            inValue.Body.tipo_deuda = tipo_deuda;
            return ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarValoresPorFechaCancelacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionResponse Presentacion.sr_rdi_rde.ExtractosSoap.ListarValoresPorFechaConstitucion(Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequest request) {
            return base.Channel.ListarValoresPorFechaConstitucion(request);
        }
        
        public Presentacion.sr_rdi_rde.ArrayOfValor ListarValoresPorFechaConstitucion(System.DateTime fecConstitucion, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequest inValue = new Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequestBody();
            inValue.Body.fecConstitucion = fecConstitucion;
            inValue.Body.tipo_deuda = tipo_deuda;
            Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionResponse retVal = ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarValoresPorFechaConstitucion(inValue);
            return retVal.Body.ListarValoresPorFechaConstitucionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionResponse> Presentacion.sr_rdi_rde.ExtractosSoap.ListarValoresPorFechaConstitucionAsync(Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequest request) {
            return base.Channel.ListarValoresPorFechaConstitucionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionResponse> ListarValoresPorFechaConstitucionAsync(System.DateTime fecConstitucion, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequest inValue = new Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarValoresPorFechaConstitucionRequestBody();
            inValue.Body.fecConstitucion = fecConstitucion;
            inValue.Body.tipo_deuda = tipo_deuda;
            return ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarValoresPorFechaConstitucionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.sr_rdi_rde.ListarValoresPorFechaValorResponse Presentacion.sr_rdi_rde.ExtractosSoap.ListarValoresPorFechaValor(Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequest request) {
            return base.Channel.ListarValoresPorFechaValor(request);
        }
        
        public Presentacion.sr_rdi_rde.ArrayOfValor ListarValoresPorFechaValor(System.DateTime fechaValor, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequest inValue = new Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequestBody();
            inValue.Body.fechaValor = fechaValor;
            inValue.Body.tipo_deuda = tipo_deuda;
            Presentacion.sr_rdi_rde.ListarValoresPorFechaValorResponse retVal = ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarValoresPorFechaValor(inValue);
            return retVal.Body.ListarValoresPorFechaValorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarValoresPorFechaValorResponse> Presentacion.sr_rdi_rde.ExtractosSoap.ListarValoresPorFechaValorAsync(Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequest request) {
            return base.Channel.ListarValoresPorFechaValorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ListarValoresPorFechaValorResponse> ListarValoresPorFechaValorAsync(System.DateTime fechaValor, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequest inValue = new Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ListarValoresPorFechaValorRequestBody();
            inValue.Body.fechaValor = fechaValor;
            inValue.Body.tipo_deuda = tipo_deuda;
            return ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ListarValoresPorFechaValorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.sr_rdi_rde.ResumenSaldosResponse Presentacion.sr_rdi_rde.ExtractosSoap.ResumenSaldos(Presentacion.sr_rdi_rde.ResumenSaldosRequest request) {
            return base.Channel.ResumenSaldos(request);
        }
        
        public Presentacion.sr_rdi_rde.ArrayOfSaldo ResumenSaldos(System.DateTime fechaLiquidacion, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ResumenSaldosRequest inValue = new Presentacion.sr_rdi_rde.ResumenSaldosRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ResumenSaldosRequestBody();
            inValue.Body.fechaLiquidacion = fechaLiquidacion;
            inValue.Body.tipo_deuda = tipo_deuda;
            Presentacion.sr_rdi_rde.ResumenSaldosResponse retVal = ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ResumenSaldos(inValue);
            return retVal.Body.ResumenSaldosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ResumenSaldosResponse> Presentacion.sr_rdi_rde.ExtractosSoap.ResumenSaldosAsync(Presentacion.sr_rdi_rde.ResumenSaldosRequest request) {
            return base.Channel.ResumenSaldosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.sr_rdi_rde.ResumenSaldosResponse> ResumenSaldosAsync(System.DateTime fechaLiquidacion, string tipo_deuda) {
            Presentacion.sr_rdi_rde.ResumenSaldosRequest inValue = new Presentacion.sr_rdi_rde.ResumenSaldosRequest();
            inValue.Body = new Presentacion.sr_rdi_rde.ResumenSaldosRequestBody();
            inValue.Body.fechaLiquidacion = fechaLiquidacion;
            inValue.Body.tipo_deuda = tipo_deuda;
            return ((Presentacion.sr_rdi_rde.ExtractosSoap)(this)).ResumenSaldosAsync(inValue);
        }
    }
}
